package enums.doenca;

public enum EsquemadeTratamentoUtilizado {
    Infecções_por_Pv_com_Cloroquina_em_três_dias_e_Primaquina_em_sete_dias,
    Infecções_por_Pf_com_Quinina_em_tres_dias_Doxiciclina_em_cinco_dias_primaquina_no_sexto_dia,
    Infecções_mistas_por_Pv_mais_Pf_com_Mefloquina_em_dose_única_e_primaquina_em_sete_dias,
    Infecções_por_Pm_com_cloroquina_em_tres_dias,
    Infecções_por_Pv_em_crianças_apresentando_vômitos_com_cápsulas_retais_de_artesunato_em_quatro_dias_e_Primaquina_em_sete_dias,
    Infecções_por_Pf_com_Mefloquina_em_dose_única_e_primaquina_no_segundo_dia,
    Infecções_por_Pf_com_Quinina_em_sete_dias,
    Infecções_por_Pf_de_crianças_com_cápsulas_retais_de_artesunato_em_quatro_dias_e_dose_única_de_Mefloquina_no_Terceiro_dia_e_Primaquina_no_Quinto_ida,
    Infecções_mistas_por_Pv_mais_Pf_com_Quinina_em_tres_dias_doxiciclina_em_5_dias_e_Primaquina_em_sete_dia,
    Prevenção_de_recaída_da_malária_por_Pv_com_Cloroquina_em_dose_única_semanal_durante_três_meses,
    Malária_grave_e_complicada,
    Infecções_por_Pf_com_a_associação_Artemeter_mais_Lumerfantrin_a_em_três_dias,
    Outro_esquema_utilizado_por_médico_descreve
}
